name: Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
            registry: ${{ secrets.DOCKER_DOMAIN }}
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Preset Image Name
      run: echo "IMAGE_URL=$(echo ${{ secrets.DOCKER_DOMAIN }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build the Docker image 
      run: docker build --no-cache -t ${{ env.IMAGE_URL }} .

    - name: Docker Push with specific commit hash
      run: docker push ${{ env.IMAGE_URL }}

    - name: Deploy Image to CapRrover
      uses: caprover/deploy-from-github@v1.1.2
      with:
        server: "${{ secrets.CAPROVER_SERVER }}"
        app: "${{ secrets.APP_NAME }}"
        token: "${{ secrets.APP_TOKEN }}"
        image: ${{ env.IMAGE_URL }}
